### ISSUE TITLE
Breakers is not in the list of color schemes

### ISSUE THREAD

**Issue by AmjadHD** [deathaxe/sublime-ui#1]
I can't find Breakers in the list of color schemes.

**Comment by deathaxe** [comment]
This ui.py is a drop in replacement for the one of ST's Default package. It was created to propose some patches to the core devs during the last dev cycle. It's based on ST3140 and was never updated with more recent releases. 

Therefore it does not support the new _*.sublime-color-scheme_ extension which Breakers uses.
